# ZeaBur 部署配置 - NeuroMemory
# 完整部署：应用 + Neo4j + Qdrant

# =============================================================================
# NeuroMemory 主应用服务
# =============================================================================
services:
  - name: neuromemory-api
    type: webservice
    build:
      dockerfile: Dockerfile
    env:
      # HTTP 服务器配置
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8765

      # LLM 配置 - DeepSeek（生产环境推荐）
      LLM_PROVIDER: deepseek
      DeepSeekApiKey: # 在 ZeaBur 控制台添加此变量

      # Embedding 配置 - SiliconFlow（成本更低）
      EMBEDDING_PROVIDER: siliconflow
      SiliconFlowApiKey: # 在 ZeaBur 控制台添加此变量

      # 数据库连接：依赖 neo4j-neuromemory / qdrant-neuromemory 后，ZeaBur 会注入
      # NEO4J_NEUROMEMORY_HOST、QDRANT_NEUROMEMORY_HOST；config.py 会自动使用。
      # 若需覆盖，可在控制台设置 NEO4J_URL、QDRANT_HOST。
      NEO4J_USERNAME: neo4j
      Neo4jPassword: # 在 ZeaBur 控制台添加此变量
      QDRANT_PORT: 6400

      # Session 管理配置
      SESSION_TIMEOUT: 1800        # 30 分钟超时
      SESSION_MAX_DURATION: 86400   # 最大 24 小时
      SESSION_MAX_EVENTS: 100      # 最多 100 条事件

      # 启用图谱存储
      ENABLE_GRAPH_STORE: true

    ports:
      - port: 8765
        public: true
        healthCheck:
          httpPath: /health
          interval: 30
          timeout: 10
          initialDelay: 40

    depends_on:
      - neo4j-neuromemory
      - qdrant-neuromemory

    # 资源配置
    resources:
      cpu: 0.5
      memory: 1Gi

    # 扩展配置
    # 重要：当前 Session 存储在内存中，不支持多实例共享。
    # 若配置 max > 1，会导致 Session 跨实例丢失（/end-session 返回 "No active session"）。
    # 多实例支持需先实现 Redis Session 存储，参见 docs/ARCHITECTURE.md。
    scaling:
      min: 1
      max: 1
      targetCPUUtilization: 70

# =============================================================================
# Neo4j 图数据库服务
# =============================================================================
  - name: neo4j-neuromemory
    type: prebuilt
    prebuiltType: neo4j
    version: "5.26"

    env:
      # 认证配置
      NEO4J_AUTH: neo4j/{{ neuromemory-api.env.Neo4jPassword }}

      # 启用插件
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

      # 安全配置（允许插件函数）
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*

      # 性能优化配置
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 2G

    ports:
      - port: 7474
        public: false      # Web 界面仅内部访问
      - port: 17687
        public: false      # Bolt 协议仅内部访问

    resources:
      cpu: 1
      memory: 4Gi

    volumes:
      - name: neo4j-data
        mountTo: /data
        size: 20Gi

# =============================================================================
# Qdrant 向量数据库服务
# =============================================================================
  - name: qdrant-neuromemory
    type: prebuilt
    prebuiltType: qdrant
    version: latest

    env:
      QDRANT__SERVICE__HTTP_PORT: "6400"

      # 性能优化配置
      QDRANT__STORAGE__PERFORMANCE__MAX_OPTIMIZATION_THREADS: 2
      QDRANT__SERVICE__GRPC_PORT: "6334"

    ports:
      - port: 6400
        public: false      # API 仅内部访问
      - port: 6334
        public: false      # gRPC 仅内部访问

    resources:
      cpu: 0.5
      memory: 2Gi

    volumes:
      - name: qdrant-data
        mountTo: /qdrant/storage
        size: 10Gi
